### ISSUE TITLE
Exception with Xamarin.VisualStudio "file already exists"

### ISSUE THREAD

**Issue by matthiaslischka** [godotengine/godot-csharp-visualstudio#24]
Hi,
I'm stuck with the installer because it fails with the Xamarin.VisualStudio package.

```
29.01.2022 19:42:38 - Package 'Xamarin.VisualStudio,version=17.0.0.343' failed to install. System.IO.IOException: The file 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Microsoft.Common.CrossTargeting.Targets\ImportBefore\Xamarin.Common.CrossTargeting.targets' already exists.
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.<InstallCoreInternal>g__install|31_1(PackagePart part, Boolean saveExtensionManifest, <>c__DisplayClass31_0& , <>c__DisplayClass31_1& , <>c__DisplayClass31_2& , <>c__DisplayClass31_3& , <>c__DisplayClass31_4& )
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.InstallCoreInternal(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.<>c__DisplayClass7_0.<InstallCore>b__0()
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.DoAction(Func`1 action)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.InstallCore(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.InstallerBase.InstallHelper(InstallData installData)
```

I'm just wondering if that's something you have control of or if its a "visual studio extensions installer" thing.
Failing an installer because a file already exists seems kinda _wrong_.

BR Matthias

**Comment by matthiaslischka** [comment]
Even uninstalling Xamarin via the Visual Studio Installer did not fix this issue.

**Comment by matthiaslischka** [comment]
Ok, WOW. This installer is really error-prone and self-sabotaging.
When the installer fails half way through and you resolve that issue, on the next run it will fail because the files it copied in the first install attempt already exist. Are you kidding me? 🤣

It would be really great, a necessity really, if the installer could just ignore files that "already exist" when the are just the same. 
Especially if they already exist because the installer itself copied them to that location on the last try 2 minutes ago.

My solution now was to first uninstall Xamarin via Visual Studio Installer, then run the installer several time to get a list of all files that it has issues with and before each try delete all those files by hand. Somehow that worked.

BR Matthias

**Comment by BenMcLean** [comment]
I agree. Recommend checking if the file size is the same for this.

**Comment by neikeq** [comment]
> I'm just wondering if that's something you have control of or if its a "visual studio extensions installer" thing.

We only tell Visual Studio that we need the Xamarin component, but we don't actually control how it's installed:

https://github.com/godotengine/godot-csharp-visualstudio/blob/f286e2942d985eed195e4a7b71317deb663233e7/GodotAddinVS/source.extension.vsixmanifest#L50

We need that component in order to be able to use the Mono debugger.

**Comment by Alriightyman** [comment]
I got this error too. However, my issue was I needed to have the Visual Studio installer install the "mobile development with .NET" tools.  After that, the addon installed just fine.

**Comment by larinius** [comment]
Installer creates file, and later says "file already exists". Its obviously bug in installer code.

`Package 'Xamarin.VisualStudio,version=17.1.0.309' failed to install. System.IO.IOException: The file 'd:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets' already exists.`
