### ISSUE TITLE
Cannot install it for visual studio 2022

### ISSUE THREAD

**Issue by userqt** [godotengine/godot-csharp-visualstudio#29]
I am using visual studio 2022 and godot 3.4.4 both x64. I downloaded the extension and hit install. After some time I got this error:
How to make it work?

Package 'Xamarin.VisualStudio,version=17.2.0.177' failed to install. System.IO.IOException: The file 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\Microsoft.VisualStudio.RemoteControl.dll' already exists.
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.<InstallCoreInternal>g__install|31_1(PackagePart part, Boolean saveExtensionManifest, <>c__DisplayClass31_0& , <>c__DisplayClass31_1& , <>c__DisplayClass31_2& , <>c__DisplayClass31_3& , <>c__DisplayClass31_4& )
   at Microsoft.VisualStudio.Setup.Installer.VsixInstaller.InstallCoreInternal(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.<>c__DisplayClass7_0.<InstallCore>b__0()
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.DoAction(Func`1 action)
   at Microsoft.VisualStudio.Setup.Installer.FileInstaller.InstallCore(String localPath, String installDir, InstallablePackage pkg)
   at Microsoft.VisualStudio.Setup.Installer.InstallerBase.InstallHelper(InstallData installData)

**Comment by userqt** [comment]
Ok, I seem to made it install. Not sure what went wrong. I had Desktop development with C++ selected altogether with c# .net development. So I removed the C++ one and used modify for visual studio. Then installed the plugin successfully.

**Comment by Houdini111** [comment]
Thanks for posting your findings. I removed all my C++ components 
Desktop development with C++ 
Mobile development with C++
Game development with C++
And that fixed it for me as well.
