### ISSUE TITLE
VS 2017 Community throws NoApplicableSKUsException

### ISSUE THREAD

**Issue by GuiltyPixel** [godotengine/godot-csharp-visualstudio#4]
Extension refuses to install on VS 2017 Community

![image](https://user-images.githubusercontent.com/12185502/86700149-7c726600-bfd6-11ea-9b37-c590efa4ed8f.png)

```
7/6/2020 22:12:11 - Microsoft VSIX Installer
7/6/2020 22:12:11 - -------------------------------------------
7/6/2020 22:12:11 - vsixinstaller.exe version:
7/6/2020 22:12:11 - 16.5.2047
7/6/2020 22:12:11 - -------------------------------------------
7/6/2020 22:12:11 - Command line parameters:
7/6/2020 22:12:11 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\bunni\Downloads\GodotAddinVS.vsix
7/6/2020 22:12:11 - -------------------------------------------
7/6/2020 22:12:11 - Microsoft VSIX Installer
7/6/2020 22:12:11 - -------------------------------------------
7/6/2020 22:12:14 - Skipping product Microsoft.VisualStudio.Product.BuildTools (a8ba3e0d) since it does not support extensions
7/6/2020 22:12:14 - Initializing Install...
7/6/2020 22:12:16 - Extension Details...
7/6/2020 22:12:16 - 	Identifier         : GodotAddinVS
7/6/2020 22:12:16 - 	Name               : Godot Support
7/6/2020 22:12:16 - 	Author             : Ignacio Roldán Etcheverry
7/6/2020 22:12:16 - 	Version            : 1.1.1
7/6/2020 22:12:16 - 	Description        : Support for Godot Engine C# projects, including debugging and extended code completion.
7/6/2020 22:12:16 - 	Locale             : en-US
7/6/2020 22:12:16 - 	MoreInfoURL        : 
7/6/2020 22:12:16 - 	InstalledByMSI     : False
7/6/2020 22:12:16 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - 	SignatureState     : Unsigned
7/6/2020 22:12:16 - 	Supported Products : 
7/6/2020 22:12:16 - 		Microsoft.VisualStudio.Community
7/6/2020 22:12:16 - 			Version : [16.0,17.0)
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - 	References         : 
7/6/2020 22:12:16 - 		-------------------------------------------------------
7/6/2020 22:12:16 - 		Identifier   : Microsoft.VisualStudio.MPF.16.0
7/6/2020 22:12:16 - 		Name         : Visual Studio MPF 16.0
7/6/2020 22:12:16 - 		Version      : [16.0,)
7/6/2020 22:12:16 - 		MoreInfoURL  : 
7/6/2020 22:12:16 - 		Nested       : No
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - 	Prerequisites      : 
7/6/2020 22:12:16 - 		-------------------------------------------------------
7/6/2020 22:12:16 - 		Identifier   : Microsoft.VisualStudio.Component.MonoDebugger
7/6/2020 22:12:16 - 		Name         : Mono debugger
7/6/2020 22:12:16 - 		Version      : [16.0,)
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - 		-------------------------------------------------------
7/6/2020 22:12:16 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/6/2020 22:12:16 - 		Name         : Visual Studio core editor
7/6/2020 22:12:16 - 		Version      : [16.0,)
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - 		-------------------------------------------------------
7/6/2020 22:12:16 - 		Identifier   : Microsoft.VisualStudio.Component.Roslyn.LanguageServices
7/6/2020 22:12:16 - 		Name         : Roslyn Language Services
7/6/2020 22:12:16 - 		Version      : [16.0,)
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - 		-------------------------------------------------------
7/6/2020 22:12:16 - 		Identifier   : Component.Xamarin
7/6/2020 22:12:16 - 		Name         : Xamarin
7/6/2020 22:12:16 - 		Version      : [16.6.30013.169,17.0)
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - Signature Details...
7/6/2020 22:12:16 - 	Extension is not signed.
7/6/2020 22:12:16 - 
7/6/2020 22:12:16 - Searching for applicable products...
7/6/2020 22:12:16 - Found installed product - Global Location
7/6/2020 22:12:16 - Found installed product - Visual Studio Community 2017
7/6/2020 22:12:16 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by neikeq** [comment]
Only VS2019 is supported.
Damn, looks like I forgot to mention this anywhere.
